spring:
  #数据库配置
  datasource:
    username: test_order
    password: 61NNT9RJSLwGelGy
    url: jdbc:mysql://rm-bp1y256043o82d4wa.mysql.rds.aliyuncs.com:3306/mutual_odps?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf-8


dubbo:
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://127.0.0.1:2181
#  scan:
#    basePackages: com.qsc.plan.provider



##xxl-jobs
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses:
    executor:
      appname: publicity-service-job-executor
      ip:
      port: 9998
      ### xxl-job log path
      logpath: /tmp/publicity-service/xxl-job-log/
      ### xxl-job log retention days
      logretentiondays: -1
    accessToken:
