

## Dubbo
dubbo:
  application:
    name: data-api-consumer
    qos-port: 20222
  registry:
    address: zookeeper://127.0.0.1:2181


##xxl-jobs
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses:
    executor:
      appname: copy-data-job-executor
      ip:
      port: 9998
      ### xxl-job log path
      logpath: /tmp/publicity-service/xxl-job-log/
      ### xxl-job log retention days
      logretentiondays: -1
    accessToken: